language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
 - DB=MYSQL CORE_RELEASE=3.2 PDO=1
 - DB=MYSQL CORE_RELEASE=3.2

before_script:
  - composer self-update
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit mwm-utilities/tests/